all:
  hosts:
    node1:
      ansible_host: 159.69.192.215
      ip: 159.69.192.215
      access_ip: 159.69.192.215
    node2:
      ansible_host: 159.69.192.159
      ip: 159.69.192.159
      access_ip: 159.69.192.159
    node3:
      ansible_host: 159.69.193.67
      ip: 159.69.193.67
      access_ip: 159.69.193.67
    node4:
      ansible_host: 94.130.168.205
      ip: 94.130.168.205
      access_ip: 94.130.168.205
    node5:
      ansible_host: 157.90.122.56
      ip: 157.90.122.56
      access_ip: 157.90.122.56
    node6:
      ansible_host: 157.90.126.75
      ip: 157.90.126.75
      access_ip: 157.90.126.75

  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
