all:
  hosts:
    node1:
      ansible_host: 159.69.192.215
      ip: 159.69.192.215
      access_ip: 159.69.192.215
    node2:
      ansible_host: 159.69.192.159
      ip: 159.69.192.159
      access_ip: 159.69.192.159
    node3:
      ansible_host: 159.69.193.67
      ip: 159.69.193.67
      access_ip: 159.69.193.67
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
