all:
  hosts:
    node1:
      ansible_host: 192.168.2.2
      ip: 192.168.2.2
      access_ip: 192.168.2.2
    node2:
      ansible_host: 192.168.2.3
      ip: 192.168.2.3
      access_ip: 192.168.2.3
    node3:
      ansible_host: 192.168.2.4
      ip: 192.168.2.4
      access_ip: 192.168.2.4
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
